Title: Images

fields:
  colorextractor:
    label: Color extractor
    type: colorextractor
  files:
    headline: Images
    type: files
    template: color
  bgcolor:
    label: Background Color
    type: color
  alt:
    label: Description de l'image
    type: text
