title: Project

columns:
  left:
    width: 1/2
    sections:
      gallery:
        type: files
        layout: cards
        images:
          cover: true
          ratio: 1/1
  right:
    width: 1/2
    sections:
      Headline:
        type: fields
        fields:
          titre:
            type: text
          Texte:
            type: textarea
